### ISSUE TITLE
possible evaluation error

### ISSUE THREAD

**Issue by francesc79** [buttonwoodcx/bcx-expression-evaluator#5]
when  evaluate 'null >= 0' the evaluetor return null instead that true. This is a bug?

Thank

**Comment by 3cp** [comment]
This is in original `aurelia-binding` implementation. I am surprised too it did special treatment on null and undefined not only for `+` and `-` operators.

If I comment out the last `return null;`, it will let `>=` go through as normal. Let me ask aurelia teammates first before I make this "fix".

https://github.com/buttonwoodcx/bcx-expression-evaluator/blob/9d5ff4753eb6b30752b10067f87ccbf1df60d1dd/src/ast.js#L271-L285

**Comment by 3cp** [comment]
Aurelia expression tried to mitigate weird JS behaviours (there is lots of unexpected result from null, undefined, NaN...), it was designed mainly to be used in Aurelia html view template where it tried to normalise some weird JS behaviours (which was a debatable decision) as much as possible.

The other side of the story is if you rely on the behaviour of `null >= 0` (which is an edge case) in your business logic, you probably owe a null check.

I am going to remove the `return null;` to restore the standard JS behaviour for other operators rather than `+` and `-`. Because this edge case behaviour is not documented for this library, I will list it as a "fix" instead of a breaking change.

Release soon :-)
